apiVersion: apps/v1
kind: Deployment
metadata: 
  name: calculator-app
  labels:
    app: calculator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-app

  template:
    metadata:
      labels:
       app: calculator-app

    spec:
      conatainers:
      - name: calculator-app
        image: devopstraning1235/calculator-app:13
        ports:
        - containerPort: 5000
