apiVersion: apps/v1
kind: Deployment
metadata: 
  name: calculator-app
  labels:
    app: calculator-app
spec:
  replicas: 2
  selector:
    matchLables:
      app: calculator-app

  template:
    metadata:
      lables:
       app: calculator-app

  spec:
    conatainers:
    - name: calculator-app
      image: devopstraning1235/calculator-app:replaceImageTag
      ports:
      - containerPort: 5000
