# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 5000
  type: NodePort
