# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 5000
      #nodePort: 30000
  type: NodePort
